package com.ud.ai.chat.service;

import org.springframework.ai.audio.tts.TextToSpeechPrompt;
import org.springframework.ai.audio.tts.TextToSpeechResponse;
import org.springframework.ai.openai.OpenAiAudioSpeechModel;
import org.springframework.ai.openai.OpenAiAudioSpeechOptions;
import org.springframework.ai.openai.api.OpenAiAudioApi;
import org.springframework.stereotype.Service;

@Service
public class OpenAIAudioGenerateService {

    private final OpenAiAudioSpeechModel speechModel;

    public OpenAIAudioGenerateService(OpenAiAudioSpeechModel speechModel) {
        this.speechModel = speechModel;
    }

    /**
     * Convert the text into voice and return the mp3 as a byte array.
     *<pre>
     * Response: the audio file generated by OpenAI is attached( resources/output_files/speech.mp3)
     * </pre>
     * @param text
     * @return byte[] mp3 audio data
     */
    public byte[] generateSpeech(String text) {

        var options = OpenAiAudioSpeechOptions.builder()
                .model("tts-1-hd")
                .voice(OpenAiAudioApi.SpeechRequest.Voice.ALLOY) // ALLOY, ECHO, FABLE, ONYX, NOVA, SHIMMER
                .responseFormat(OpenAiAudioApi.SpeechRequest.AudioResponseFormat.MP3)
                .speed(1.0d) // 0.25 to 4.0
                .build();

        TextToSpeechPrompt speechPrompt = new TextToSpeechPrompt(text, options);
        TextToSpeechResponse speechResponse = speechModel.call(speechPrompt);

        return speechResponse.getResult().getOutput();
    }
}
